---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/SALab/IPAM/IPAM_Methods/IPAM_Acquire_from_MIQ"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - ActivateCMDB:
      value: "/SELAE/Infrastructure/VM/Provisioning/execute_code/execute_code"
